version: '3'
services:



  postgresql-service:
    image: postgres:9.4.1


  summoner2-service:
    image: ra/summoner2-service:v1
    ports:
      - "8080:8080"
    environment:
       DB_HOST: "postgresql-service"
       ALLOWED_CORS: "${FRONTEND_HOSTNAME}"
    

  # mysql-service:
  #   image: mysql/mysql-server:5.6 
  #   depends_on:
  #     - "eureka-service"
    
  #   environment:
  #      MYSQL_ROOT_HOST: "%" 
  #      MYSQL_ROOT_PASSWORD: db-password
  #      MYSQL_DATABASE: db_example 

  #   command: --lower_case_table_names=1 --init-connect='GRANT CREATE USER ON *.* TO 'root'@'%';FLUSH PRIVILEGES;'
  #   # ports:
  #   #   - "3306:3306" 
  #   volumes:
  #     - /tmp:/tmp
    